version: "3.8"

services:
  reserva:
    image: reserva-salas
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./room_booking.db:/app/room_booking.db
    stdin_open: true
    tty: true

  app:
    build: .
    container_name: room_booking_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app

  redis:
    image: redis:7.2
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
