name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dev tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Ruff (lint)
        run: |
          ruff format --check .
          ruff check .

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dev tools
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
      - name: Run tests
        run: |
          pytest -q --cov=. --cov-report=term-missing

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build zipapp (dist/room_booking.pyz)
        shell: bash
        run: |
          mkdir -p dist
          python - <<'PY'
          from pathlib import Path
          from zipapp import create_archive

          EXCLUDE = {
              '.git', '.github', 'tests', 'dist', 'artifacts', '__pycache__',
              '.ruff_cache', '.pytest_cache', '.venv', 'venv', 'env'
          }

          def keep(path: Path) -> bool:
              # path es un Path relativo dentro del proyecto
              return not any(part in EXCLUDE for part in path.parts)

          create_archive(
              source='.',
              target='dist/room_booking.pyz',
              main='main:main',
              filter=keep,
          )
          PY
          du -h dist/room_booking.pyz || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
