name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: read
  security-events: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install Ruff
        run: pip install ruff
      - name: Run Ruff Lint
        run: ruff check . --fix

  test:
    runs-on: ubuntu-latest
    needs: lint
    services:
      redis:
        image: redis:7.2
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install requests ruff

      - name: Run Tests with Coverage
        run: |
          mkdir -p artifacts
          pytest -q --cov=. \
            --cov-report=xml:artifacts/coverage.xml \
            --cov-report=html:artifacts/htmlcov \
            --junitxml=artifacts/junit.xml

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: artifacts

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Build App (zip)
        run: |
          mkdir -p dist
          zip -r dist/room_booking.zip . \
            -x "venv/*" "__pycache__/*" ".pytest_cache/*" ".git/*" "*.db" "artifacts/*" "dist/*"
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist
          retention-days: 5

  codeql:
    name: CodeQL Security Analysis
    needs: build
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:python"
