name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: requirements-dev.txt
      - name: Instalar herramientas de desarrollo
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Ruff (formato + lint)
        run: |
          ruff format --check .
          ruff check .

  test:
    runs-on: ubuntu-22.04
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: requirements-dev.txt
      - name: Instalar herramientas de desarrollo
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Ejecutar tests con cobertura (XML + JUnit)
        run: |
          mkdir -p artifacts
          pytest -q \
            --cov=. \
            --cov-report=xml:artifacts/coverage.xml \
            --junitxml=artifacts/junit.xml
      - name: Subir artifacts de tests y cobertura
        uses: actions/upload-artifact@v4
        with:
          name: test-and-coverage
          path: artifacts

  build:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - name: Liberar espacio en disco
        run: |
          sudo rm -rf /usr/local/lib/android || true
          sudo rm -rf /usr/share/dotnet || true
          sudo rm -rf /opt/ghc || true
          sudo rm -rf "$AGENT_TOOLSDIRECTORY" || true
          sudo journalctl --rotate || true
          sudo journalctl --vacuum-time=1s || true
          df -h
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          lfs: false
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build zipapp (dist/room_booking.pyz) excluyendo directorios pesados
        shell: bash
        run: |
          mkdir -p dist
          python - <<'PY'
          from zipapp import create_archive
          EXCLUDE = {
              '.git', '.github', 'tests', 'dist', 'artifacts', '__pycache__',
              '.ruff_cache', '.pytest_cache', '.venv', 'venv', 'env'
          }
          def keep(path: str) -> bool:
              parts = path.split('/')
              return not any(p in EXCLUDE for p in parts) and path != ''
          create_archive(
              source='.',
              target='dist/room_booking.pyz',
              main='main:main',
              filter=keep,
          )
          PY
          du -h dist/room_booking.pyz || true

      - name: Subir artifact de build (dist)
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          retention-days: 5
