name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: requirements-dev.txt
      - name: Install dev tools
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Ruff (lint + format check)
        run: |
          ruff format --check .
          ruff check .

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: requirements-dev.txt
      - name: Install dev tools
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run unit tests with coverage
        run: |
          mkdir -p artifacts
          pytest -q \
            --cov=. \
            --junitxml=artifacts/junit.xml
      - name: Upload test & coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-and-coverage
          path: artifacts

  build:
    runs-on: ubuntu-22.04  
    steps:
      - name: Free disk space (logs + SDKs pesados)
        run: |
          sudo rm -rf /usr/local/lib/android || true
          sudo rm -rf /usr/share/dotnet || true
          sudo rm -rf /opt/ghc || true
          sudo rm -rf "$AGENT_TOOLSDIRECTORY" || true
          sudo journalctl --rotate || true
          sudo journalctl --vacuum-time=1s || true
          df -h
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Build zipapp (dist/room_booking.pyz)
        run: |
          mkdir -p dist
          python -c "from zipapp import create_archive; create_archive('.', target='dist/room_booking.pyz', main='main:main')"
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          retention-days: 5


